project_id = "qmolpddcyzedcehddsjn"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false
